# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
lang: es
title: "Mi Argentina"
description: "Documentación de integración del inicio de sesión de Mi Argentina para las distintas plataformas de la APN."

baseurl: "/mi-argentina" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# source: src
# destination: dist

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass